"""Translation mappings for API parameters from English to Chinese."""

translate: dict[str, str] = {
    "article_number": "法條編號",
    "bill_flow_status": "議案流程.狀態",
    "bill_no": "議案編號",
    "bill_no_nested": "議事網資料.關係文書.議案.議案編號",
    "bill_number": "議案編號",
    "bill_status": "議案狀態",
    "bill_type": "議案類別",
    "co_proposer": "連署人",
    "committee_code": "委員會代號",
    "committee_type": "委員會類別",
    "comt_cd": "委員會代號",
    "date": "日期",
    "law_number": "法律編號",
    "law_number_nested": "議事網資料.關係文書.議案.法律編號",
    "limit": "限制筆數",
    "meet_id": "會議資料.會議編號",
    "meeting_code": "會議代碼",
    "meeting_type": "會議種類",
    "member": "會議資料.出席委員",
    "output_fields": "輸出欄位",
    "page": "頁數",
    "proposal_date": "提案日期",
    "proposal_number": "提案編號",
    "proposal_source": "提案來源",
    "proposer": "提案人",
    "reference_number": "字號",
    "session": "會期",
    "term": "屆",
}
